# Generated by Django 6.1.1 on 2026-09-04 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_code', models.CharField(max_length=10)),
                ('driver_number', models.PositiveIntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('driver_code', 'driver_number')},
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('circuit', models.CharField(max_length=150)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='races.season')),
            ],
            options={
                'ordering': ['season__year', 'round_number'],
                'unique_together': {('season', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('R', 'Race'), ('Q', 'Qualifying')], max_length=2)),
                ('air_temp', models.FloatField(blank=True, null=True)),
                ('track_temp', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('rainfall', models.BooleanField(default=False)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='races.race')),
            ],
            options={
                'unique_together': {('race', 'session_type')},
            },
        ),
        migrations.CreateModel(
            name='PitStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.PositiveIntegerField()),
                ('duration_seconds', models.FloatField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pit_stops', to='races.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pit_stops', to='races.session')),
            ],
            options={
                'ordering': ['session', 'lap_number'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='races.season')),
            ],
            options={
                'unique_together': {('season', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.PositiveIntegerField()),
                ('lap_time_seconds', models.FloatField(blank=True, null=True)),
                ('sector1_seconds', models.FloatField(blank=True, null=True)),
                ('sector2_seconds', models.FloatField(blank=True, null=True)),
                ('sector3_seconds', models.FloatField(blank=True, null=True)),
                ('compound', models.CharField(blank=True, max_length=20)),
                ('tyre_life', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('is_pit_lap', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='races.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='races.session')),
            ],
            options={
                'ordering': ['session', 'lap_number'],
                'unique_together': {('session', 'driver', 'lap_number')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishing_position', models.PositiveIntegerField(blank=True, null=True)),
                ('grid_position', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.FloatField(default=0)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('q1_seconds', models.FloatField(blank=True, null=True)),
                ('q2_seconds', models.FloatField(blank=True, null=True)),
                ('q3_seconds', models.FloatField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='races.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='races.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='races.team')),
            ],
            options={
                'ordering': ['session', 'finishing_position'],
                'unique_together': {('session', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='DriverSeasonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_entries', to='races.driver')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_entries', to='races.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_entries', to='races.team')),
            ],
            options={
                'unique_together': {('driver', 'season')},
            },
        ),
    ]
