# Generated by Django 6.1.1 on 2026-09-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
